name: coffee_http_client
description: >
  A minimal, opinionated HTTP client for Flutter and Dart.
  Designed for explicit request lifecycles, predictable behavior,
  and application-defined response handling.

version: 0.0.1
homepage: https://github.com/HylkeReinders/coffee_http_client
repository: https://github.com/HylkeReinders/coffee_http_client
issue_tracker: https://github.com/HylkeReinders/coffee_http_client/issues

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
